name: Publish Kevin Core
on:
  push:
    branches: [ main, test-publish ]
env:
  MAJOR_VERSION: "1.0"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
        name: Install Dependencies
        working-directory: ./kevin.core  
      - run: npm version  $MAJOR_VERSION.${{ github.run_number }}-alpha
        name: Bump Kevin Core package's version.
        working-directory: ./kevin.core    
      - run: npm publish
        working-directory: ./kevin.core
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}