name: Kevin Publish Redis Provider docker

on:
  push:
    branches: [main]
    paths:
      - kevin.core/**
      - kevin.redis/**
      - kevin.server/**
      - kevin.client/**
      - .github/workflows/kevin-redis-provider-docker-publish.yaml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PAT }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/kevin-redis-provider:latest,${{ secrets.DOCKERHUB_USERNAME }}/kevin-reids-provider:${{ vars.MAJOR_VERSION }}.${{ github.run_number }}-alpha
          labels: version=${{ vars.MAJOR_VERSION }}.${{ github.run_number }}-alpha
