name: Kevin PR

on:
  pull_request:
    paths:
      - kevin.core/**
      - kevin.core.tests/**
  push:
    branches: [ main ]
    paths:
      - kevin.core/**
      - kevin.core.tests/**
  
    

jobs:
  build_kevin_core:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x, 16.x, 17.x, 18.x]

    steps:
      - uses: actions/checkout@v3
      - name:  CI Kevin Core (Node.js ${{ matrix.node-version }})
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
        working-directory: ./kevin.core
      - run: npm run lint
        working-directory: ./kevin.core
      - run: npm run build --if-present
        working-directory: ./kevin.core
      - run: npm ci
        working-directory: ./kevin.core.tests
      - run: npm test
        working-directory: ./kevin.core.tests
