name: Kevin Server PR

on:
  pull_request:
    paths:
      - kevin.server/**
      - kevin.core/**
  push:
    branches: [ main ]
    paths:
      - kevin.server/**

jobs:
  build_kevin_server:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [17.x, 18.x]
    steps:
      - uses: actions/checkout@v3
      - name:  CI Kevin Server (Node.js ${{ matrix.node-version }})
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm run build:allDependencies
        working-directory: ./kevin.server
        name: Build All Dependencies
      - run: npm ci
        name: Kevin-Server install Dependencies
        working-directory: ./kevin.server
      - run: npm run build --if-present
        name: Build Kevin Server
        working-directory: ./kevin.server
      - run: npm run lint
        working-directory: ./kevin.server

 