name: Publish Redis Provider
on:
  push:
    branches: [ main ]
    paths:
      - kevin.redis/**
env:
  MAJOR_VERSION: "1.0"
jobs:
  publish-redis-provider:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm run build:allDependencies
        working-directory: ./kevin.redis
        name: Building dependencies
      - run: npm ci
        working-directory: ./kevin.redis
        name: Install Redis Provider dependencies
      - run: npm run build --if-present
        working-directory: ./kevin.redis
        name: Build Redis Provider
      - run: npm version $MAJOR_VERSION.${{ github.run_number }}-alpha
        name: Bump Redis provider package's version.
        working-directory: ./kevin.redis    
      - run: npm publish --access=public
        working-directory: ./kevin.redis
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}