name: Kevin Redis Provider PR

on:
  pull_request:
    paths:
      - kevin.redis/**
      - kevin.core/**
  push:
    branches: [ main ]
    paths:
      - kevin.redis/**

jobs:
  build_redis_provider:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [17.x, 18.x]
    steps:
      - uses: actions/checkout@v3
      - name:  CI Redis Provider (Node.js ${{ matrix.node-version }})
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm run build:allDependencies
        working-directory: ./kevin.redis
        name: Building dependencies
      - run: npm ci
        working-directory: ./kevin.redis
        name: Install Redis Provider dependencies
      - run: npm run build --if-present
        working-directory: ./kevin.redis
        name: Build Redis Provider
      - run: npm run lint
        working-directory: ./kevin.redis
        name: Lint Redis Provider

 