name: Kevin Release website
on:
  pull_request:
    paths:
      - kevin.server/**
      - kevin.ui/**
      - .github/workflows/kevin-release.yaml

jobs:
  build_aws_provider:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3
      - name: Release Website
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm run install:solution
        name: Installing dependencies
      - run: npm run build:solution
        name: Building dependencies
      - run: npm run ui:copy-dist
        name: Copy UI dist.
      - name: Zip solution
        uses: vimtor/action-zip@v1.1
        with:
          files: kevin.server/dist kevin.server/package.json
          dest: kevin.server.zip
      - uses: 'marvinpinto/action-automatic-releases@latest'
        with:
          repo_token: '${{ secrets.GITHUB_TOKEN }}'
          prerelease: true
          draft: true
          title: 'Kevin Release test'
          files: |
            kevin.server.zip
