name: Publish AWS Provider
on:
  push:
    branches: [ main ]
    paths:
      - kevin.aws/**
      - github/workflows/kevin-aws-provider-publish.yaml

jobs:
  publish-aws-provider:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm run build:allDependencies
        working-directory: ./kevin.aws
        name: Building dependencies
      - run: npm ci
        working-directory: ./kevin.aws
        name: Install AWS Provider dependencies
      - run: npm run build --if-present
        working-directory: ./kevin.aws
        name: Build AWS Provider
      - run: npm version ${{ vars.MAJOR_VERSION }}.${{ github.run_number }}-alpha
        name: Bump ReAWSdis provider package's version.
        working-directory: ./kevin.aws    
      - run: npm publish --access=public
        working-directory: ./kevin.aws
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}